const teams = [
  {
    name: 'JSS',
    roster: [
      'Rory McIlroy',
      'Collin Morikawa',
      'Brooks Koepka',
      'Tommy Fleetwood',
      'Tom Hoge',
      'Chris Kirk',
      'Jason Kokrak',
      'Gordon Sargent',
    ],
  },
  {
    name: 'Rusty',
    roster: [
      'Rory McIlroy',
      'Xander Schauffele',
      'Will Zalatoris',
      'Min Woo Lee',
      'Si Woo Kim',
      'Chris Kirk',
      'Adam Svensson',
      'Sam Bennett',
    ],
  },
  {
    name: 'President Kennedy',
    roster: [
      'Scottie Scheffler',
      'Dustin Johnson',
      'Viktor Hovland',
      'Tyrrell Hatton',
      'Louis Oosthuizen',
      'Talor Gooch',
      'Cameron Champ',
      'Vijay Singh',
    ],
  },
  {
    name: 'Shark',
    roster: [
      'Rory McIlroy',
      'Cameron Young',
      'Brooks Koepka',
      'Tyrrell Hatton',
      'Tom Hoge',
      'Chris Kirk',
      'Harris English',
      'Gordon Sargent',
    ],
  },
  {
    name: 'Mr Miller',
    roster: [
      'Scottie Scheffler',
      'Max Homa',
      'Corey Conners',
      'Min Woo Lee',
      'Si Woo Kim',
      'Kurt Kitayama',
      'Charl Schwartzel',
      'Gordon Sargent',
    ],
  },
  {
    name: 'Zman',
    roster: [
      'Scottie Scheffler',
      'Cameron Smith',
      'Sungjae Im',
      'Joaquin Niemann',
      'Abraham Ancer',
      'Chris Kirk',
      'Mackenzie Hughes',
      'Gordon Sargent',
    ],
  },
  {
    name: 'Dpickle',
    roster: [
      'Jordan Spieth',
      'Cameron Smith',
      'Corey Conners',
      'Tiger Woods',
      'Louis Oosthuizen',
      'Talor Gooch',
      'Jason Kokrak',
      'Fred Couples',
    ],
  },
  {
    name: 'SamRab',
    roster: [
      'Rory McIlroy',
      'Collin Morikawa',
      'Viktor Hovland',
      'Tiger Woods',
      'Adam Scott',
      'Bubba Watson',
      'Phil Mickelson',
      'Fred Couples',
    ],
  },
  {
    name: 'Kcheese',
    roster: [
      'Rory McIlroy',
      'Cameron Smith',
      'Will Zalatoris',
      'Tommy Fleetwood',
      'Louis Oosthuizen',
      'Alex Noren',
      'Harris English',
      'Gordon Sargent',
    ],
  },
  {
    name: 'Bennos',
    roster: [
      'Scottie Scheffler',
      'Cameron Smith',
      'Corey Conners',
      'Tyrrell Hatton',
      'Sahith Theegala',
      'Kurt Kitayama',
      'Cameron Champ',
      'Gordon Sargent',
    ],
  },
  {
    name: 'Glassy',
    roster: [
      'Justin Thomas',
      'Collin Morikawa',
      'Will Zalatoris',
      'Justin Rose',
      'Sahith Theegala',
      'Talor Gooch',
      'Cameron Champ',
      'Mike Weir',
    ],
  },
  {
    name: 'Pistol',
    roster: [
      'Justin Thomas',
      'Cameron Young',
      'Brooks Koepka',
      'Tiger Woods',
      'Adam Scott',
      'Kurt Kitayama',
      'Cameron Champ',
      'Ben Carr',
    ],
  },
  {
    name: 'McSpurr',
    roster: [
      'Jon Rahm',
      'Cameron Smith',
      'Viktor Hovland',
      'Justin Rose',
      'Sahith Theegala',
      'Kurt Kitayama',
      'Mackenzie Hughes',
      'Sam Bennett',
    ],
  },
  {
    name: 'Gut',
    roster: [
      'Scottie Scheffler',
      'Collin Morikawa',
      'Sam Burns',
      'Joaquin Niemann',
      'Tom Hoge',
      'Brian Harman',
      'Mackenzie Hughes',
      'Sam Bennett',
    ],
  },
  {
    name: "Earle's Law",
    roster: [
      'Rory McIlroy',
      'Cameron Young',
      'Sungjae Im',
      'Tyrrell Hatton',
      'Sahith Theegala',
      'Russell Henley',
      'Harris English',
      'Aldrich Potgieter',
    ],
  },
];

export { teams };
